### ISSUE TITLE
Having issues replicating deploy errors from getshifter.io

### ISSUE THREAD

**Issue by fabioelia** [getshifter/shifter-artifact-helper#86]
Having issues with artifacts not deploying on the main site 
<img width="851" alt="image" src="https://github.com/getshifter/shifter-artifact-helper/assets/633247/6bfee6d4-10ab-4a4a-80e3-77a303b9c6ec">

Site stopped being able to generate artifacts this week out of the blue, haven't had any luck via the dev logs. Fixed any "fatal" errors initially and just see some warning and deprecation warnings, but can't get any more detail when I actually trigger a build deploy (no new errors in the log) I have to restart the container with the theme disabled (and then can successfully enable it once its up and running :()

So I cloned this repo, set it up locally with same data / content / plugins that are deployed on the main site, still not seeing any issues. I'm able to hit the `?urls` endpoint which I imagine its using to see what pages to generate static content for.  Was really hoping this repo could shed some more light but not seeing anything. Not getting anywhere with support 

<img width="856" alt="image" src="https://github.com/getshifter/shifter-artifact-helper/assets/633247/e8bf25af-df5a-45a8-a8f3-47f66d943425">

**Comment by plastikdreams** [comment]
Hello.
The issue you are inquiring about might not be a bug report for this script but something you should discuss with support. Please reach out to the support chat on https://go.getshifter.io/ for assistance.

Thanks.

**Comment by fabioelia** [comment]
I'm fairly positive the issue is not with the wordpress instance but in the logic being run on deployment
